<?php

use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = 
        [
            ['Ahuachapán', 1],
            ['Apaneca', 1],
            ['Atiquizaya', 1],
            ['Concepción de Ataco', 1],
            ['El Refugio', 1],
            ['Guaymango', 1],
            ['Jujutla', 1],
            ['San Francisco Menéndez', 1],
            ['San Lorenzo', 1],
            ['San Pedro Puxtla', 1],
            ['Tacuba', 1],
            ['Turín', 1],
            ['Acajutla', 2],
            ['Armenia', 2],
            ['Caluco', 2],
            ['Cuisnahuat', 2],
            ['Izalco', 2],
            ['Juaypua', 2],
            ['Nahuizalco', 2],
            ['San Antonio del Monte', 2],
            ['San Julión', 2],
            ['Santa Catarina Masahuat', 2],
            ['Santa Isabel Ishuatán', 2],
            ['Santo Domingo de Guzmán', 2],
            ['Sonsonate', 2],
            ['Sonzacate', 2],
            ['Candelaria de la Frontera', 3],
            ['Chalchuapa', 3],
            ['Coatepeque', 3],
            ['El Congo', 3],
            ['El Porvenir', 3],
            ['Masahuat', 3],
            ['Metapán', 3],
            ['San Antonio Pajonal', 3],
            ['San Sebastián Salitrillo', 3],
            ['Santa Ana', 3],
            ['Santa Rosa Guachipilín', 3],
            ['Santiago de la Frontera', 3],
            ['Santa Ana', 3],
            ['Cinquera', 4],
            ['Villa Dolores', 4],
            ['Guacotecti', 4],
            ['Ilobasco', 4],
            ['Jutiapa', 4],
            ['San Isidro', 4],
            ['Sensuntepeque', 4],
            ['Tejutepeque', 4],
            ['Victoria', 4],
            ['Agua Caliente', 5],
            ['Arcatao', 5],
            ['Azacualpa', 5],
            ['Chalatenango', 5],
            ['Citalá', 5],
            ['Comalapa', 5],
            ['Concepción Quezaltepeque', 5],
            ['Dulce Nombre de María', 5],
            ['El Carrizal', 5],
            ['El Paraíso', 5],
            ['La Laguna', 5],
            ['La Palma', 5],
            ['La Reina', 5],
            ['Las Vueltas', 5],
            ['Nombre de Jesús', 5],
            ['Nueva Concepción', 5],
            ['Nueva Trinidad', 5],
            ['Ojos de Agua', 5],
            ['Potonico', 5],
            ['San Antonio de la Cruz', 5],
            ['San Antonio de Los Ranchos', 5],
            ['San Fernando', 5],
            ['San Francisco Lempa', 5],
            ['San Ignacio', 5],
            ['San Francisco Morán', 5],
            ['San Isidro Labrador', 5],
            ['San José Cancasque', 5],
            ['San José Las Flores', 5],
            ['San Luis del Carmen', 5],
            ['San Miguel de Mercedes', 5],
            ['San Rafael', 5],
            ['Santa Rita', 5],
            ['Tejutla', 5],
            ['Candelaria', 6],
            ['Cojutepeque', 6],
            ['El Carmen', 6],
            ['El Rosario', 6],
            ['Monte San Juan', 6],
            ['Oratorio de Concepción', 6],
            ['San Bartolomé Perulapía', 6],
            ['San Cristobal', 6],
            ['San José Guayabal', 6],
            ['San Pedro Perulapán', 6],
            ['San Rafael Cedros', 6],
            ['San Ramón', 6],
            ['Santa Cruz Analquito', 6],
            ['Santa Cruz Michapa', 6],
            ['Suchitoto', 6],
            ['Tenancingo', 6],
            ['Antiguo Cuscatlán', 7],
            ['Chiltiupán', 7],
            ['Ciudad Arce', 7],
            ['Colón', 7],
            ['La Libertad', 7],
            ['Santa Tecla', 7],
            ['Nuevo Cuscatlán', 7],
            ['San Juan Opico', 7],
            ['Quezaltepeque', 7],
            ['Sacacoyo', 7],
            ['San José Villanueva', 7],
            ['San Matías', 7],
            ['San Pablo Tacachico', 7],
            ['Talnique', 7],
            ['Tamanique', 7],
            ['Teotepeque', 7],
            ['Tepecoyo', 7],
            ['Zaragoza', 7],
            ['Cuyultitán', 8],
            ['Rosario de La Paz', 8],
            ['Jerusalén', 8],
            ['Mercedes de la Ceiba', 8],
            ['Olocuilta', 8],
            ['Paraíso de Osorio', 8],
            ['San Antonio Masahuat', 8],
            ['San Emigdio', 8],
            ['San Francisco Chinameca', 8],
            ['San Juan Nonualco', 8],
            ['San Juan Talpa', 8],
            ['San Matías', 8],
            ['San Juan Tepezontes', 8],
            ['San Luis La Herradura', 8],
            ['San Luis Talpa', 8],
            ['San Miguel Tepezontes', 8],
            ['San Pedro Masahuat', 8],
            ['San Pedro Nonualco', 8],
            ['San Rafael Obrajuelo', 8],
            ['Santa María Ostuma', 8],
            ['Santiago Nonualco', 8],
            ['Tapalhuaca', 8],
            ['Zacatecoluca', 8],
            ['Aguilares', 9],
            ['Apopa', 9],
            ['Ayutuxtepeque', 9],
            ['Ciudad Delgado', 9],
            ['Cuscatancingo', 9],
            ['El Paisnal', 9],
            ['Guazapa', 9],
            ['Ilopango', 9],
            ['Mejicanos', 9],
            ['Nejapa', 9],
            ['Panchimalco', 9],
            ['Rosario de Mora', 9],
            ['San Marcos', 9],
            ['San Martín', 9],
            ['San Salvador', 9],
            ['Santiago Texacuangos', 9],
            ['Santo Tomás', 9],
            ['Soyapango', 9],
            ['Tonacatepeque', 9],
            ['Apastepeque', 10],
            ['Guadalupe', 10],
            ['San Cayetano Istepeque', 10],
            ['San Esteban Catarina', 10],
            ['San Ildefonso', 10],
            ['San Lorenzo', 10],
            ['San Sebastián', 10],
            ['San Vicente', 10],
            ['Santa Clara', 10],
            ['Santo Domingo', 10],
            ['Tecoluca', 10],
            ['Tepetitán', 10],
            ['Verapaz', 10],
            ['Arambala', 11],
            ['Cacaopera', 11],
            ['Chilanga', 11],
            ['Corinto', 11],
            ['Delicias de Concepción', 11],
            ['El Divisadero', 11],
            ['El Rosario', 11],
            ['Gualococti', 11],
            ['Guatajiagua', 11],
            ['Joateca', 11],
            ['Jocoaitique', 11],
            ['Jocoro', 11],
            ['Lolotiquillo', 11],
            ['Meanguera', 11],
            ['Osicala', 11],
            ['Perquín', 11],
            ['San Carlos', 11],
            ['San Fernando', 11],
            ['San Francisco Gotera', 11],
            ['San Isidro', 11],
            ['San Simón', 11],
            ['Sensembra', 11],
            ['Sociedad', 11],
            ['Torola', 11],
            ['Yamabal', 11],
            ['Yoloaiquín', 11],
            ['Carolina', 12],
            ['Chapeltique', 12],
            ['Chinameca', 12],
            ['Chirilagua', 12],
            ['Ciudad Barrios', 12],
            ['Comoacarán', 12],
            ['El Tránsito', 12],
            ['Lolotique', 12],
            ['San Antonio del Mosco', 12],
            ['San Gerardo', 12],
            ['San Jorge', 12],
            ['San Luis de la Reina', 12],
            ['San Miguel', 12],
            ['San Rafael Oriente', 12],
            ['Sesori', 12],
            ['Uluazapa', 12],
            ['Alegría', 13],
            ['Berlín', 13],
            ['California', 13],
            ['Concepción Batres', 13],
            ['El Triunfo', 13],
            ['Ereguayquín', 13],
            ['Estanzuelas', 13],
            ['Jiquilisco', 13],
            ['Jucuapa', 13],
            ['Jucuarán', 13],
            ['Mercedes Umaña', 13],
            ['Nueva Granada', 13],
            ['Ozatlán', 13],
            ['Puerto El Triunfo', 13],
            ['Puerto el triunfo', 13],
            ['San Agustín', 13],
            ['San Buenaventura', 13],
            ['San Dionisio', 13],
            ['San Francisco de Javier', 13],
            ['Santa Elena', 13],
            ['Santa María', 13],
            ['Santiago de María', 13],
            ['Tecapán', 13],
            ['Usulután', 13],
            ['Anamoros', 14],
            ['Bolívar', 14],
            ['Concepción de Oriente', 14],
            ['Conchagua', 14],
            ['El Carmen', 14],
            ['El Sauce', 14],
            ['Intipuca', 14],
            ['La Unión', 14],
            ['Poloros', 14],
            ['San Alejo', 14],
            ['San José', 14],
            ['Santa Rosa de Lima', 14],
            ['Yayantique', 14],
            ['Yucuaiquán', 14]
        ];

        foreach ($datos as $m) {
            App\Municipio::create($m);
        }
    }
}
