<?php

use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = 
        [
            ['nombre' => 'Ahuachapán', 'departamento_id' => 1],
            ['nombre' => 'Apaneca', 'departamento_id' => 1],
            ['nombre' => 'Atiquizaya', 'departamento_id' => 1],
            ['nombre' => 'Concepción de Ataco', 'departamento_id' => 1],
            ['nombre' => 'El Refugio', 'departamento_id' => 1],
            ['nombre' => 'Guaymango', 'departamento_id' => 1],
            ['nombre' => 'Jujutla', 'departamento_id' => 1],
            ['nombre' => 'San Francisco Menéndez', 'departamento_id' => 1],
            ['nombre' => 'San Lorenzo', 'departamento_id' => 1],
            ['nombre' => 'San Pedro Puxtla', 'departamento_id' => 1],
            ['nombre' => 'Tacuba', 'departamento_id' => 1],
            ['nombre' => 'Turín', 'departamento_id' => 1],
            ['nombre' => 'Acajutla', 'departamento_id' => 2],
            ['nombre' => 'Armenia', 'departamento_id' => 2],
            ['nombre' => 'Caluco', 'departamento_id' => 2],
            ['nombre' => 'Cuisnahuat', 'departamento_id' => 2],
            ['nombre' => 'Izalco', 'departamento_id' => 2],
            ['nombre' => 'Juaypua', 'departamento_id' => 2],
            ['nombre' => 'Nahuizalco', 'departamento_id' => 2],
            ['nombre' => 'San Antonio del Monte', 'departamento_id' => 2],
            ['nombre' => 'San Julión', 'departamento_id' => 2],
            ['nombre' => 'Santa Catarina Masahuat', 'departamento_id' => 2],
            ['nombre' => 'Santa Isabel Ishuatán', 'departamento_id' => 2],
            ['nombre' => 'Santo Domingo de Guzmán', 'departamento_id' => 2],
            ['nombre' => 'Sonsonate', 'departamento_id' => 2],
            ['nombre' => 'Sonzacate', 'departamento_id' => 2],
            ['nombre' => 'Candelaria de la Frontera', 'departamento_id' => 3],
            ['nombre' => 'Chalchuapa', 'departamento_id' => 3],
            ['nombre' => 'Coatepeque', 'departamento_id' => 3],
            ['nombre' => 'El Congo', 'departamento_id' => 3],
            ['nombre' => 'El Porvenir', 'departamento_id' => 3],
            ['nombre' => 'Masahuat', 'departamento_id' => 3],
            ['nombre' => 'Metapán', 'departamento_id' => 3],
            ['nombre' => 'San Antonio Pajonal', 'departamento_id' => 3],
            ['nombre' => 'San Sebastián Salitrillo', 'departamento_id' => 3],
            ['nombre' => 'Santa Ana', 'departamento_id' => 3],
            ['nombre' => 'Santa Rosa Guachipilín', 'departamento_id' => 3],
            ['nombre' => 'Santiago de la Frontera', 'departamento_id' => 3],
            ['nombre' => 'Santa Ana', 'departamento_id' => 3],
            ['nombre' => 'Cinquera', 'departamento_id' => 4],
            ['nombre' => 'Villa Dolores', 'departamento_id' => 4],
            ['nombre' => 'Guacotecti', 'departamento_id' => 4],
            ['nombre' => 'Ilobasco', 'departamento_id' => 4],
            ['nombre' => 'Jutiapa', 'departamento_id' => 4],
            ['nombre' => 'San Isidro', 'departamento_id' => 4],
            ['nombre' => 'Sensuntepeque', 'departamento_id' => 4],
            ['nombre' => 'Tejutepeque', 'departamento_id' => 4],
            ['nombre' => 'Victoria', 'departamento_id' => 4],
            ['nombre' => 'Agua Caliente', 'departamento_id' => 5],
            ['nombre' => 'Arcatao', 'departamento_id' => 5],
            ['nombre' => 'Azacualpa', 'departamento_id' => 5],
            ['nombre' => 'Chalatenango', 'departamento_id' => 5],
            ['nombre' => 'Citalá', 'departamento_id' => 5],
            ['nombre' => 'Comalapa', 'departamento_id' => 5],
            ['nombre' => 'Concepción Quezaltepeque', 'departamento_id' => 5],
            ['nombre' => 'Dulce Nombre de María', 'departamento_id' => 5],
            ['nombre' => 'El Carrizal', 'departamento_id' => 5],
            ['nombre' => 'El Paraíso', 'departamento_id' => 5],
            ['nombre' => 'La Laguna', 'departamento_id' => 5],
            ['nombre' => 'La Palma', 'departamento_id' => 5],
            ['nombre' => 'La Reina', 'departamento_id' => 5],
            ['nombre' => 'Las Vueltas', 'departamento_id' => 5],
            ['nombre' => 'Nombre de Jesús', 'departamento_id' => 5],
            ['nombre' => 'Nueva Concepción', 'departamento_id' => 5],
            ['nombre' => 'Nueva Trinidad', 'departamento_id' => 5],
            ['nombre' => 'Ojos de Agua', 'departamento_id' => 5],
            ['nombre' => 'Potonico', 'departamento_id' => 5],
            ['nombre' => 'San Antonio de la Cruz', 'departamento_id' => 5],
            ['nombre' => 'San Antonio de Los Ranchos', 'departamento_id' => 5],
            ['nombre' => 'San Fernando', 'departamento_id' => 5],
            ['nombre' => 'San Francisco Lempa', 'departamento_id' => 5],
            ['nombre' => 'San Ignacio', 'departamento_id' => 5],
            ['nombre' => 'San Francisco Morán', 'departamento_id' => 5],
            ['nombre' => 'San Isidro Labrador', 'departamento_id' => 5],
            ['nombre' => 'San José Cancasque', 'departamento_id' => 5],
            ['nombre' => 'San José Las Flores', 'departamento_id' => 5],
            ['nombre' => 'San Luis del Carmen', 'departamento_id' => 5],
            ['nombre' => 'San Miguel de Mercedes', 'departamento_id' => 5],
            ['nombre' => 'San Rafael', 'departamento_id' => 5],
            ['nombre' => 'Santa Rita', 'departamento_id' => 5],
            ['nombre' => 'Tejutla', 'departamento_id' => 5],
            ['nombre' => 'Candelaria', 'departamento_id' => 6],
            ['nombre' => 'Cojutepeque', 'departamento_id' => 6],
            ['nombre' => 'El Carmen', 'departamento_id' => 6],
            ['nombre' => 'El Rosario', 'departamento_id' => 6],
            ['nombre' => 'Monte San Juan', 'departamento_id' => 6],
            ['nombre' => 'Oratorio de Concepción', 'departamento_id' => 6],
            ['nombre' => 'San Bartolomé Perulapía', 'departamento_id' => 6],
            ['nombre' => 'San Cristobal', 'departamento_id' => 6],
            ['nombre' => 'San José Guayabal', 'departamento_id' => 6],
            ['nombre' => 'San Pedro Perulapán', 'departamento_id' => 6],
            ['nombre' => 'San Rafael Cedros', 'departamento_id' => 6],
            ['nombre' => 'San Ramón', 'departamento_id' => 6],
            ['nombre' => 'Santa Cruz Analquito', 'departamento_id' => 6],
            ['nombre' => 'Santa Cruz Michapa', 'departamento_id' => 6],
            ['nombre' => 'Suchitoto', 'departamento_id' => 6],
            ['nombre' => 'Tenancingo', 'departamento_id' => 6],
            ['nombre' => 'Antiguo Cuscatlán', 'departamento_id' => 7],
            ['nombre' => 'Chiltiupán', 'departamento_id' => 7],
            ['nombre' => 'Ciudad Arce', 'departamento_id' => 7],
            ['nombre' => 'Colón', 'departamento_id' => 7],
            ['nombre' => 'La Libertad', 'departamento_id' => 7],
            ['nombre' => 'Santa Tecla', 'departamento_id' => 7],
            ['nombre' => 'Nuevo Cuscatlán', 'departamento_id' => 7],
            ['nombre' => 'San Juan Opico', 'departamento_id' => 7],
            ['nombre' => 'Quezaltepeque', 'departamento_id' => 7],
            ['nombre' => 'Sacacoyo', 'departamento_id' => 7],
            ['nombre' => 'San José Villanueva', 'departamento_id' => 7],
            ['nombre' => 'San Matías', 'departamento_id' => 7],
            ['nombre' => 'San Pablo Tacachico', 'departamento_id' => 7],
            ['nombre' => 'Talnique', 'departamento_id' => 7],
            ['nombre' => 'Tamanique', 'departamento_id' => 7],
            ['nombre' => 'Teotepeque', 'departamento_id' => 7],
            ['nombre' => 'Tepecoyo', 'departamento_id' => 7],
            ['nombre' => 'Zaragoza', 'departamento_id' => 7],
            ['nombre' => 'Cuyultitán', 'departamento_id' => 8],
            ['nombre' => 'Rosario de La Paz', 'departamento_id' => 8],
            ['nombre' => 'Jerusalén', 'departamento_id' => 8],
            ['nombre' => 'Mercedes de la Ceiba', 'departamento_id' => 8],
            ['nombre' => 'Olocuilta', 'departamento_id' => 8],
            ['nombre' => 'Paraíso de Osorio', 'departamento_id' => 8],
            ['nombre' => 'San Antonio Masahuat', 'departamento_id' => 8],
            ['nombre' => 'San Emigdio', 'departamento_id' => 8],
            ['nombre' => 'San Francisco Chinameca', 'departamento_id' => 8],
            ['nombre' => 'San Juan Nonualco', 'departamento_id' => 8],
            ['nombre' => 'San Juan Talpa', 'departamento_id' => 8],
            ['nombre' => 'San Matías', 'departamento_id' => 8],
            ['nombre' => 'San Juan Tepezontes', 'departamento_id' => 8],
            ['nombre' => 'San Luis La Herradura', 'departamento_id' => 8],
            ['nombre' => 'San Luis Talpa', 'departamento_id' => 8],
            ['nombre' => 'San Miguel Tepezontes', 'departamento_id' => 8],
            ['nombre' => 'San Pedro Masahuat', 'departamento_id' => 8],
            ['nombre' => 'San Pedro Nonualco', 'departamento_id' => 8],
            ['nombre' => 'San Rafael Obrajuelo', 'departamento_id' => 8],
            ['nombre' => 'Santa María Ostuma', 'departamento_id' => 8],
            ['nombre' => 'Santiago Nonualco', 'departamento_id' => 8],
            ['nombre' => 'Tapalhuaca', 'departamento_id' => 8],
            ['nombre' => 'Zacatecoluca', 'departamento_id' => 8],
            ['nombre' => 'Aguilares', 'departamento_id' => 9],
            ['nombre' => 'Apopa', 'departamento_id' => 9],
            ['nombre' => 'Ayutuxtepeque', 'departamento_id' => 9],
            ['nombre' => 'Ciudad Delgado', 'departamento_id' => 9],
            ['nombre' => 'Cuscatancingo', 'departamento_id' => 9],
            ['nombre' => 'El Paisnal', 'departamento_id' => 9],
            ['nombre' => 'Guazapa', 'departamento_id' => 9],
            ['nombre' => 'Ilopango', 'departamento_id' => 9],
            ['nombre' => 'Mejicanos', 'departamento_id' => 9],
            ['nombre' => 'Nejapa', 'departamento_id' => 9],
            ['nombre' => 'Panchimalco', 'departamento_id' => 9],
            ['nombre' => 'Rosario de Mora', 'departamento_id' => 9],
            ['nombre' => 'San Marcos', 'departamento_id' => 9],
            ['nombre' => 'San Martín', 'departamento_id' => 9],
            ['nombre' => 'San Salvador', 'departamento_id' => 9],
            ['nombre' => 'Santiago Texacuangos', 'departamento_id' => 9],
            ['nombre' => 'Santo Tomás', 'departamento_id' => 9],
            ['nombre' => 'Soyapango', 'departamento_id' => 9],
            ['nombre' => 'Tonacatepeque', 'departamento_id' => 9],
            ['nombre' => 'Apastepeque', 'departamento_id' => 10],
            ['nombre' => 'Guadalupe', 'departamento_id' => 10],
            ['nombre' => 'San Cayetano Istepeque', 'departamento_id' => 10],
            ['nombre' => 'San Esteban Catarina', 'departamento_id' => 10],
            ['nombre' => 'San Ildefonso', 'departamento_id' => 10],
            ['nombre' => 'San Lorenzo', 'departamento_id' => 10],
            ['nombre' => 'San Sebastián', 'departamento_id' => 10],
            ['nombre' => 'San Vicente', 'departamento_id' => 10],
            ['nombre' => 'Santa Clara', 'departamento_id' => 10],
            ['nombre' => 'Santo Domingo', 'departamento_id' => 10],
            ['nombre' => 'Tecoluca', 'departamento_id' => 10],
            ['nombre' => 'Tepetitán', 'departamento_id' => 10],
            ['nombre' => 'Verapaz', 'departamento_id' => 10],
            ['nombre' => 'Arambala', 'departamento_id' => 11],
            ['nombre' => 'Cacaopera', 'departamento_id' => 11],
            ['nombre' => 'Chilanga', 'departamento_id' => 11],
            ['nombre' => 'Corinto', 'departamento_id' => 11],
            ['nombre' => 'Delicias de Concepción', 'departamento_id' => 11],
            ['nombre' => 'El Divisadero', 'departamento_id' => 11],
            ['nombre' => 'El Rosario', 'departamento_id' => 11],
            ['nombre' => 'Gualococti', 'departamento_id' => 11],
            ['nombre' => 'Guatajiagua', 'departamento_id' => 11],
            ['nombre' => 'Joateca', 'departamento_id' => 11],
            ['nombre' => 'Jocoaitique', 'departamento_id' => 11],
            ['nombre' => 'Jocoro', 'departamento_id' => 11],
            ['nombre' => 'Lolotiquillo', 'departamento_id' => 11],
            ['nombre' => 'Meanguera', 'departamento_id' => 11],
            ['nombre' => 'Osicala', 'departamento_id' => 11],
            ['nombre' => 'Perquín', 'departamento_id' => 11],
            ['nombre' => 'San Carlos', 'departamento_id' => 11],
            ['nombre' => 'San Fernando', 'departamento_id' => 11],
            ['nombre' => 'San Francisco Gotera', 'departamento_id' => 11],
            ['nombre' => 'San Isidro', 'departamento_id' => 11],
            ['nombre' => 'San Simón', 'departamento_id' => 11],
            ['nombre' => 'Sensembra', 'departamento_id' => 11],
            ['nombre' => 'Sociedad', 'departamento_id' => 11],
            ['nombre' => 'Torola', 'departamento_id' => 11],
            ['nombre' => 'Yamabal', 'departamento_id' => 11],
            ['nombre' => 'Yoloaiquín', 'departamento_id' => 11],
            ['nombre' => 'Carolina', 'departamento_id' => 12],
            ['nombre' => 'Chapeltique', 'departamento_id' => 12],
            ['nombre' => 'Chinameca', 'departamento_id' => 12],
            ['nombre' => 'Chirilagua', 'departamento_id' => 12],
            ['nombre' => 'Ciudad Barrios', 'departamento_id' => 12],
            ['nombre' => 'Comoacarán', 'departamento_id' => 12],
            ['nombre' => 'El Tránsito', 'departamento_id' => 12],
            ['nombre' => 'Lolotique', 'departamento_id' => 12],
            ['nombre' => 'San Antonio del Mosco', 'departamento_id' => 12],
            ['nombre' => 'San Gerardo', 'departamento_id' => 12],
            ['nombre' => 'San Jorge', 'departamento_id' => 12],
            ['nombre' => 'San Luis de la Reina', 'departamento_id' => 12],
            ['nombre' => 'San Miguel', 'departamento_id' => 12],
            ['nombre' => 'San Rafael Oriente', 'departamento_id' => 12],
            ['nombre' => 'Sesori', 'departamento_id' => 12],
            ['nombre' => 'Uluazapa', 'departamento_id' => 12],
            ['nombre' => 'Alegría', 'departamento_id' => 13],
            ['nombre' => 'Berlín', 'departamento_id' => 13],
            ['nombre' => 'California', 'departamento_id' => 13],
            ['nombre' => 'Concepción Batres', 'departamento_id' => 13],
            ['nombre' => 'El Triunfo', 'departamento_id' => 13],
            ['nombre' => 'Ereguayquín', 'departamento_id' => 13],
            ['nombre' => 'Estanzuelas', 'departamento_id' => 13],
            ['nombre' => 'Jiquilisco', 'departamento_id' => 13],
            ['nombre' => 'Jucuapa', 'departamento_id' => 13],
            ['nombre' => 'Jucuarán', 'departamento_id' => 13],
            ['nombre' => 'Mercedes Umaña', 'departamento_id' => 13],
            ['nombre' => 'Nueva Granada', 'departamento_id' => 13],
            ['nombre' => 'Ozatlán', 'departamento_id' => 13],
            ['nombre' => 'Puerto El Triunfo', 'departamento_id' => 13],
            ['nombre' => 'Puerto el triunfo', 'departamento_id' => 13],
            ['nombre' => 'San Agustín', 'departamento_id' => 13],
            ['nombre' => 'San Buenaventura', 'departamento_id' => 13],
            ['nombre' => 'San Dionisio', 'departamento_id' => 13],
            ['nombre' => 'San Francisco de Javier', 'departamento_id' => 13],
            ['nombre' => 'Santa Elena', 'departamento_id' => 13],
            ['nombre' => 'Santa María', 'departamento_id' => 13],
            ['nombre' => 'Santiago de María', 'departamento_id' => 13],
            ['nombre' => 'Tecapán', 'departamento_id' => 13],
            ['nombre' => 'Usulután', 'departamento_id' => 13],
            ['nombre' => 'Anamoros', 'departamento_id' => 14],
            ['nombre' => 'Bolívar', 'departamento_id' => 14],
            ['nombre' => 'Concepción de Oriente', 'departamento_id' => 14],
            ['nombre' => 'Conchagua', 'departamento_id' => 14],
            ['nombre' => 'El Carmen', 'departamento_id' => 14],
            ['nombre' => 'El Sauce', 'departamento_id' => 14],
            ['nombre' => 'Intipuca', 'departamento_id' => 14],
            ['nombre' => 'La Unión', 'departamento_id' => 14],
            ['nombre' => 'Poloros', 'departamento_id' => 14],
            ['nombre' => 'San Alejo', 'departamento_id' => 14],
            ['nombre' => 'San José', 'departamento_id' => 14],
            ['nombre' => 'Santa Rosa de Lima', 'departamento_id' => 14],
            ['nombre' => 'Yayantique', 'departamento_id' => 14],
            ['nombre' => 'Yucuaiquán', 'departamento_id' => 14]
        ];

        foreach ($datos as $m) {
            App\Municipio::create($m);
        }
    }
}
